# Generated by Django 5.1.6 on 2025-02-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_comment_parent_comment_upvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='license',
            name='name',
            field=models.CharField(help_text='License type (e.g. Basic, Premium, Exclusive)', max_length=100),
        ),
    ]
