# Generated by Django 5.1.6 on 2025-02-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_beat_is_featured_alter_license_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beat',
            name='description',
        ),
        migrations.AddField(
            model_name='beat',
            name='type',
            field=models.CharField(choices=[('beat', 'Beat'), ('loop', 'Loop'), ('soundkit', 'Sound Kit'), ('preset', 'Preset')], default='beat', max_length=20),
        ),
        migrations.AlterField(
            model_name='beat',
            name='key',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='beat',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='beat',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
