# Generated by Django 5.1.6 on 2025-02-23 23:03

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_beat_status'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beat',
            name='tags',
        ),
        migrations.AddField(
            model_name='beat',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
