# Generated by Django 5.1.6 on 2025-02-23 23:03

from django.db import migrations

def convert_tags(apps, schema_editor):
    Beat = apps.get_model('store', 'Beat')
    for beat in Beat.objects.all():
        if hasattr(beat, '_old_tags') and beat._old_tags:
            tags = [tag.strip() for tag in beat._old_tags.split(',') if tag.strip()]
            beat.tags.add(*tags)

def reverse_convert_tags(apps, schema_editor):
    Beat = apps.get_model('store', 'Beat')
    for beat in Beat.objects.all():
        tags = list(beat.tags.names())
        if tags:
            beat._old_tags = ', '.join(tags)
            beat.save()

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_remove_beat_tags_beat_tags'),
    ]

    operations = [
        migrations.RunPython(convert_tags, reverse_convert_tags),
    ]
